[project]
name = ""
version = ""
description = ""
authors = [
    {name = "utahka", email = "utahka.akiba@gmail.com"},
]
dependencies = [
    "jupyter>=1.0.0",
]
requires-python = ">=3.11"
license = {text = "MIT"}
